<?php

/**
 * views/pest-control.php — the pest-control landing page.
 *
 * In scope from render_page(): $path, $route, $title, $description,
 * $canonical, $ogImage, $ogSize, $robots.
 *
 * The FAQ list and the four-step tuples were declared inline in the React
 * component; they stay inline here, verbatim.
 */

$pestFaqs = [
    [
        'question' => 'Which pest-control treatment do I need?',
        'answer'   => 'That depends on the pest, the evidence found, activity level, property layout and any sensitive areas. Start with an inspection or a detailed phone conversation.',
    ],
    [
        'question' => 'Are treatments safe for children and pets?',
        'answer'   => 'Safety depends on the product, placement and label directions. Always disclose children, pets and health concerns and follow preparation and re-entry instructions exactly.',
    ],
    [
        'question' => 'Do I need to leave the property?',
        'answer'   => 'Some services may require temporary vacancy while others may not. You should receive instructions specific to the proposed treatment before it starts.',
    ],
    [
        'question' => 'Can you guarantee pests will never return?',
        'answer'   => 'No responsible provider can promise that for every situation. Building condition, sanitation, neighbouring activity, weather and follow-up actions can all affect recurrence.',
    ],
];

/* [title, text] — the inline array the original mapped over. The 01–04 numbers
   it carried are now generated by the .step CSS counter, so they are no longer
   written into the markup. */
$pestSteps = [
    ['Describe', 'Share signs, rooms affected and when the activity is most noticeable.'],
    ['Prepare',  'Receive instructions on access, cleaning and what to avoid before the visit.'],
    ['Inspect',  'Review evidence, likely harbourage and factors that may support activity.'],
    ['Act',      'Discuss the proposed plan, aftercare and any follow-up that may be needed.'],
];

/* The three assurances the hero states. Each one describes how the service is
   run, not an outcome it promises. */
$pestHeroPoints = [
    'Clear preparation guidance',
    'Treatment scope explained',
    'No online payment request',
];

$pestMethod = [
    'Identify likely pest and activity areas',
    'Explain preparation before the visit',
    'Discuss products and sensitive areas',
    'Provide realistic follow-up expectations',
];

?>
<section class="hero">
    <div class="hero__media" data-parallax>
        <?php /* First hero image: never lazy-loaded. img_tag adds width/height (the CLS fix). */ ?>
        <?= img_tag('/images/pest-control-hero.webp', 'Technician inspecting for small cockroaches along a kitchen baseboard') ?>
    </div>
    <div class="hero__scrim"></div>
    <div class="wrap">
        <div class="hero__inner">
            <p class="eyebrow eyebrow--on-navy">Residential pest control in <?= e(site('primary_area')) ?></p>
            <h1 class="hero__title">Pest control starts with an inspection, <em>not a guess.</em></h1>
            <p class="lede lede--on-navy">Describe the pest, signs and affected rooms. We will discuss availability, preparation and the next suitable step for your property.</p>
            <div class="hero__actions">
                <?= phone_cta('pest_hero', 'btn btn--call btn--lg') ?>
                <a class="btn btn--onnavy btn--lg" href="#pests">Identify common signs</a>
            </div>
            <ul class="hero__points">
                <?php foreach ($pestHeroPoints as $pestHeroPoint): ?>
                    <li><?= icon('i-check') ?><span><?= e($pestHeroPoint) ?></span></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</section>

<section class="quickcall">
    <div class="wrap">
        <p><strong>Seeing pest activity now?</strong> Keep the area undisturbed if practical and call with a photo or description.</p>
        <?= phone_cta('pest_quickcall', 'btn btn--dark') ?>
    </div>
</section>

<section class="section s-paper" id="pests">
    <div class="wrap">
        <div class="sec-head sec-head--row" data-anim="rise">
            <div>
                <p class="eyebrow">Common household pests</p>
                <h2>Find the page closest to what you have noticed.</h2>
            </div>
            <p class="lede">These guides explain common signs and questions. They are not a substitute for an on-site inspection where one is needed.</p>
        </div>
        <div class="tile-grid" data-anim-group>
            <?php foreach (config('pest_types') as $pestIndex => $pestType): ?>
                <a class="tile" data-anim="rise" href="<?= e(url($pestType['href'])) ?>">
                    <span class="tile__num"><?= e(sprintf('%02d', $pestIndex + 1)) ?></span>
                    <h3><?= e($pestType['name']) ?></h3>
                    <p><?= e($pestType['blurb']) ?></p>
                    <span class="tile__more">View guide <?= icon('i-arrow-right', 'ic ic--sm') ?></span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<section class="section s-mist">
    <div class="wrap">
        <div class="split">
            <div class="stack" data-anim="left">
                <p class="eyebrow">What responsible service looks like</p>
                <h2>Target the cause, not just the sighting.</h2>
                <p class="lede">Useful pest management considers harbourage, food, moisture and entry points alongside any treatment. The recommended steps should match the evidence and the property.</p>
                <ul class="checklist">
                    <?php foreach ($pestMethod as $pestMethodItem): ?>
                        <li><?= icon('i-check') ?><span><?= e($pestMethodItem) ?></span></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <figure class="figure" data-anim="right">
                <?php /* Below the fold, so this one is lazy-loaded. */ ?>
                <?= img_tag('/images/pest-control-detail.webp', 'Targeted pest treatment along a residential exterior foundation', ['loading' => 'lazy']) ?>
                <figcaption class="figure__cap">
                    <strong>Inspect before treating</strong>
                    <span>Illustrative service image</span>
                </figcaption>
            </figure>
        </div>
    </div>
</section>

<section class="section s-white">
    <div class="wrap">
        <div class="sec-head sec-head--center" data-anim="rise">
            <p class="eyebrow">From call to follow-up</p>
            <h2>A clear four-step path.</h2>
        </div>
        <div class="steps steps--row" data-anim-group>
            <?php foreach ($pestSteps as [$stepTitle, $stepText]): ?>
                <?php /* The 01–04 badge is .step::before, a CSS counter, and it takes the
                         first grid column — so the title and text share one wrapper in
                         the second. */ ?>
                <div class="step" data-anim="rise">
                    <div>
                        <h3><?= e($stepTitle) ?></h3>
                        <p><?= e($stepText) ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<section class="section s-navy">
    <div class="wrap">
        <div class="split split--wide-right">
            <div class="stack" data-anim="left">
                <p class="eyebrow eyebrow--on-navy">Pest-control FAQs</p>
                <h2>Clear answers before treatment.</h2>
                <p class="lede lede--on-navy">Ask for instructions specific to your household and the products proposed.</p>
            </div>
            <div data-anim="right">
                <?php partial('faq', ['items' => $pestFaqs]); ?>
            </div>
        </div>
    </div>
</section>

<?php partial('call-panel', [
    'eyebrow'   => 'Call about pest activity',
    'title'     => 'The best next step begins with accurate information.',
    'placement' => 'pest_cta_panel',
]); ?>
