/**
 * The pest-control landing page.
 *
 * Call surfaces on this page: pest_hero, pest_quickcall, pest_cta_panel.
 */

import { Link } from 'react-router-dom';
import { SITE, PEST_TYPES } from '../config/site.js';
import { routeFor, pageTitle, metaText } from '../config/routes.js';
import { usePageMeta } from '../lib/usePageMeta.js';
import { pad2 } from '../lib/format.js';
import Icon from '../components/Icon.jsx';
import Img from '../components/Img.jsx';
import Faq from '../components/Faq.jsx';
import CallPanel from '../components/CallPanel.jsx';
import { PhoneCta } from '../components/PhoneLink.jsx';

const pestFaqs = [
  {
    question: 'Which pest-control treatment do I need?',
    answer:
      'That depends on the pest, the evidence found, activity level, property layout and any sensitive areas. Start with an inspection or a detailed phone conversation.',
  },
  {
    question: 'Are treatments safe for children and pets?',
    answer:
      'Safety depends on the product, placement and label directions. Always disclose children, pets and health concerns and follow preparation and re-entry instructions exactly.',
  },
  {
    question: 'Do I need to leave the property?',
    answer:
      'Some services may require temporary vacancy while others may not. You should receive instructions specific to the proposed treatment before it starts.',
  },
  {
    question: 'Can you guarantee pests will never return?',
    answer:
      'No responsible provider can promise that for every situation. Building condition, sanitation, neighbouring activity, weather and follow-up actions can all affect recurrence.',
  },
];

/* The 01–04 numbers are generated by the .step CSS counter, so they are not
   written into the markup. */
const pestSteps = [
  ['Describe', 'Share signs, rooms affected and when the activity is most noticeable.'],
  ['Prepare', 'Receive instructions on access, cleaning and what to avoid before the visit.'],
  ['Inspect', 'Review evidence, likely harbourage and factors that may support activity.'],
  ['Act', 'Discuss the proposed plan, aftercare and any follow-up that may be needed.'],
];

const pestHeroPoints = [
  'Clear preparation guidance',
  'Treatment scope explained',
  'No online payment request',
];

const pestMethod = [
  'Identify likely pest and activity areas',
  'Explain preparation before the visit',
  'Discuss products and sensitive areas',
  'Provide realistic follow-up expectations',
];

export default function PestControl() {
  const route = routeFor('/pest-control');
  usePageMeta({
    title: pageTitle(route),
    description: metaText(route.description),
    canonical: '/pest-control',
  });

  return (
    <>
      <section className="hero">
        <div className="hero__media" data-parallax="">
          <Img
            src="/images/pest-control-hero.webp"
            alt="Technician inspecting for small cockroaches along a kitchen baseboard"
            fetchPriority="high"
          />
        </div>
        <div className="hero__scrim" />
        <div className="wrap">
          <div className="hero__inner">
            <p className="eyebrow eyebrow--on-navy">
              Residential pest control in {SITE.primaryArea}
            </p>
            <h1 className="hero__title">
              Pest control starts with an inspection, <em>not a guess.</em>
            </h1>
            <p className="lede lede--on-navy">
              Describe the pest, signs and affected rooms. We will discuss availability, preparation
              and the next suitable step for your property.
            </p>
            <div className="hero__actions">
              <PhoneCta placement="pest_hero" className="btn btn--call btn--lg" />
              <a className="btn btn--onnavy btn--lg" href="#pests">
                Identify common signs
              </a>
            </div>
            <ul className="hero__points">
              {pestHeroPoints.map((point) => (
                <li key={point}>
                  <Icon id="i-check" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <section className="quickcall">
        <div className="wrap">
          <p>
            <strong>Seeing pest activity now?</strong> Keep the area undisturbed if practical and
            call with a photo or description.
          </p>
          <PhoneCta placement="pest_quickcall" className="btn btn--dark" />
        </div>
      </section>

      <section className="section s-paper" id="pests">
        <div className="wrap">
          <div className="sec-head sec-head--row" data-anim="rise">
            <div>
              <p className="eyebrow">Common household pests</p>
              <h2>Find the page closest to what you have noticed.</h2>
            </div>
            <p className="lede">
              These guides explain common signs and questions. They are not a substitute for an
              on-site inspection where one is needed.
            </p>
          </div>
          <div className="tile-grid" data-anim-group="">
            {PEST_TYPES.map((pest, i) => (
              <Link className="tile" data-anim="rise" to={pest.href} key={pest.href}>
                <span className="tile__num">{pad2(i + 1)}</span>
                <h3>{pest.name}</h3>
                <p>{pest.blurb}</p>
                <span className="tile__more">
                  View guide <Icon id="i-arrow-right" className="ic ic--sm" />
                </span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="section s-mist">
        <div className="wrap">
          <div className="split">
            <div className="stack" data-anim="left">
              <p className="eyebrow">What responsible service looks like</p>
              <h2>Target the cause, not just the sighting.</h2>
              <p className="lede">
                Useful pest management considers harbourage, food, moisture and entry points
                alongside any treatment. The recommended steps should match the evidence and the
                property.
              </p>
              <ul className="checklist">
                {pestMethod.map((item) => (
                  <li key={item}>
                    <Icon id="i-check" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
            <figure className="figure" data-anim="right">
              <Img
                src="/images/pest-control-detail.webp"
                alt="Targeted pest treatment along a residential exterior foundation"
                loading="lazy"
              />
              <figcaption className="figure__cap">
                <strong>Inspect before treating</strong>
                <span>Illustrative service image</span>
              </figcaption>
            </figure>
          </div>
        </div>
      </section>

      <section className="section s-white">
        <div className="wrap">
          <div className="sec-head sec-head--center" data-anim="rise">
            <p className="eyebrow">From call to follow-up</p>
            <h2>A clear four-step path.</h2>
          </div>
          <div className="steps steps--row" data-anim-group="">
            {pestSteps.map(([title, text]) => (
              <div className="step" data-anim="rise" key={title}>
                <div>
                  <h3>{title}</h3>
                  <p>{text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="section s-navy">
        <div className="wrap">
          <div className="split split--wide-right">
            <div className="stack" data-anim="left">
              <p className="eyebrow eyebrow--on-navy">Pest-control FAQs</p>
              <h2>Clear answers before treatment.</h2>
              <p className="lede lede--on-navy">
                Ask for instructions specific to your household and the products proposed.
              </p>
            </div>
            <div data-anim="right">
              <Faq items={pestFaqs} />
            </div>
          </div>
        </div>
      </section>

      <CallPanel
        eyebrow="Call about pest activity"
        title="The best next step begins with accurate information."
        placement="pest_cta_panel"
      />
    </>
  );
}
